name: Unit Tests - .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "StreetPatch.API/StreetPatch.API.csproj"
    - name: Build
      run: dotnet build "StreetPatch.API/StreetPatch.API.csproj" --no-restore
    - name: Test
      run: dotnet test "StreetPatch.Tests/StreetPatch.Tests.csproj" --no-build --verbosity normal
